In [1]:
import pandas as pd
import numpy as np
from random import shuffle
from copy import deepcopy
from pathlib import Path

In [4]:
data_dir = '../Data-Populated-Unfiltered/Folds/'
save_dir = '../Data-Populated-Unfiltered/Sites/'
datasets = ['C2C12', 'ESC', 'MLC', 'NBC', 'L1-I','L1-F','L1-R','L6']
clss = ['MAPK1', 'MTOR']
num_folds = 5
k_folds = 5

Path(save_dir).mkdir(parents=True, exist_ok=True)

In [5]:
data_fp = ['{}{}_{}_FLD.csv'.format(data_dir, dat,cl) for dat in datasets for cl in clss ]
class_columns = ['y.{}'.format(c) for c in clss]
fold_columns = ['F{}'.format(val+1) for val in range(num_folds)]
motifs = ['{}_motif'.format(dat) for dat in datasets]

In [9]:
data_fp = ['{}{}_{}_FLD.csv'.format(data_dir, dat,cl) for dat in datasets for cl in clss ]
save_fp = ['{}{}_{}_FLD.csv'.format(save_dir, dat,cl) for dat in datasets for cl in clss ]

In [10]:
data = []

for fp in data_fp:
    data.append(pd.read_csv(fp))

In [11]:
for df, save_f in zip(data, save_fp):
    df[['site'] + fold_columns + class_columns].to_csv(save_f, index=False)

In [12]:
df[['site'] + fold_columns + class_columns]

                      site  F1  F2  F3  F4  F5  y.MAPK1  y.MTOR
0        0610010K14RIK;68;   1   2   0   2   0        0       0
1        0610010K14RIK;72;   4   1   2   0   4        0       0
2      1110002E22RIK;1026;   4   2   0   3   2        0       0
3      1110002E22RIK;1115;   1   0   0   1   3        0       0
4      1110002E22RIK;1179;   2   0   3   4   4        0       0
...                    ...  ..  ..  ..  ..  ..      ...     ...
10366          ZZEF1;1475;   1   3   2   1   2        0       0
10367          ZZEF1;1515;   3   0   1   4   2        0       0
10368          ZZEF1;1535;   0   3   0   4   3        0       0
10369          ZZEF1;1538;   2   4   4   3   0        0       0
10370          ZZEF1;1519;   2   3   4   2   1        0       0

[10371 rows x 8 columns]